name = "EMPCA"
uuid = "e1a4e9fb-620a-4045-b313-23b3f0ae950a"
authors = ["Chistian Gilbertson <chistianjgilbertson@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
